languageCode = "zh-cn"
languageName = "简体中文"
weight = 1
title = "KA's Blog"

[params]
  displayName = "简体中文"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/blowfish_logo_transparent.png"
  description = "施工中..."

[params.author]
  name = "KioroshiAki"
  image = "img/blowfish_logo.png"
  headline = "Beta v0.1 施工中..."
  bio = "施工中..."
  email = "EndotherminUnit2@outlook.com"
  links = [
    { github = "https://github.com/kioroshiaki" },
  ]